import JSZip from "jszip";
export interface ExportManifest {
  project_name: string; version: number; exported_at: string;
  file_count: number; total_size: number; tech_stack: string[];
  files: Array<{ path: string; size: number; agent: string }>;
  setup_steps: string[]; deploy_targets: string[];
}
const EXCLUDED = [".env", ".env.local", "node_modules/", ".next/", "dist/", ".cache/", "*.secret", "*.key", "*.pem"];
export async function buildExportZip(files: Array<{ path: string; content: string; agent: string }>, manifest: ExportManifest): Promise<Buffer> {
  const zip = new JSZip();
  for (const file of files) {
    const excluded = EXCLUDED.some(p => file.path.includes(p.replace("*", "")));
    if (!excluded) zip.file(file.path, file.content);
  }
  zip.file("manifest.json", JSON.stringify(manifest, null, 2));
  zip.file("SETUP.md", `# ${manifest.project_name}\n\nGenerated by AgentForge on ${manifest.exported_at}\n\n## Setup\n${manifest.setup_steps.map((s, i) => `${i + 1}. ${s}`).join("\n")}\n`);
  return zip.generateAsync({ type: "nodebuffer", compression: "DEFLATE" });
}
