import { NextRequest, NextResponse } from "next/server";
import { requireAuth } from "@/lib/utils/auth";
import { createServerClient } from "@/lib/supabase/server";
import { createAdminClient } from "@/lib/supabase/admin";
import { encryptSecret } from "@/lib/utils/crypto";
import { checkRateLimit } from "@/lib/utils/rate-limit";
import { Octokit } from "@octokit/rest";

export async function POST(req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const user = await requireAuth(req);
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  // Rate limit: max 20 pushes per hour per user
  const allowed = await checkRateLimit(user.id, "github_push", 20, "1h");
  if (!allowed) return NextResponse.json({ error: "Rate limit exceeded" }, { status: 429 });

  const supabase = await createServerClient();
  const admin = createAdminClient();

  const { data: project } = await supabase
    .from("projects")
    .select()
    .eq("id", id)
    .eq("user_id", user.id)
    .single();
  if (!project) return NextResponse.json({ error: "Not found" }, { status: 404 });

  const { data: conn } = await supabase
    .from("github_connections")
    .select()
    .eq("user_id", user.id)
    .single();
  const token = conn?.token_enc ?? process.env.GITHUB_TOKEN ?? process.env.SECRET_GITHUB_TOKEN;
  if (!token) return NextResponse.json({ error: "No GitHub token configured" }, { status: 400 });

  const { data: files } = await supabase
    .from("project_files")
    .select("path, content")
    .eq("project_id", id)
    .eq("is_deleted", false);

  if (!files?.length) return NextResponse.json({ error: "No files to push" }, { status: 400 });

  const repoName = project.name
    .toLowerCase()
    .replace(/[^a-z0-9-]/g, "-")
    .replace(/-+/g, "-")
    .slice(0, 50);

  try {
    const octokit = new Octokit({ auth: token });
    const { data: ghUser } = await octokit.users.getAuthenticated();

    let repo;
    try {
      const { data } = await octokit.repos.get({ owner: ghUser.login, repo: repoName });
      repo = data;
    } catch {
      const { data } = await octokit.repos.createForAuthenticatedUser({
        name: repoName,
        private: false,
        auto_init: true,
        description: `Generated by AgentForge — ${project.description ?? project.name}`,
      });
      repo = data;
    }

    const { data: ref } = await octokit.git.getRef({
      owner: ghUser.login,
      repo: repoName,
      ref: "heads/main",
    });
    const baseSha = ref.object.sha;

    const treeItems = await Promise.all(
      files
        .filter((f) => f.content && f.content.length > 0)
        .map(async (f) => {
          const { data: blob } = await octokit.git.createBlob({
            owner: ghUser.login,
            repo: repoName,
            content: Buffer.from(f.content!).toString("base64"),
            encoding: "base64",
          });
          return { path: f.path, mode: "100644" as const, type: "blob" as const, sha: blob.sha };
        })
    );

    const envExample =
      "NEXT_PUBLIC_SUPABASE_URL=\nNEXT_PUBLIC_SUPABASE_ANON_KEY=\nSUPABASE_SERVICE_ROLE_KEY=\nGITHUB_MODELS_TOKEN=\nGROQ_API_KEY=\nMISTRAL_API_KEY=\nOPENROUTER_API_KEY=\nHUGGINGFACE_TOKEN=\nCLOUDFLARE_API_TOKEN=\nCLOUDFLARE_ACCOUNT_ID=\nENCRYPTION_KEY=";
    const { data: envBlob } = await octokit.git.createBlob({
      owner: ghUser.login,
      repo: repoName,
      content: Buffer.from(envExample).toString("base64"),
      encoding: "base64",
    });
    treeItems.push({ path: ".env.example", mode: "100644", type: "blob", sha: envBlob.sha });

    const { data: tree } = await octokit.git.createTree({
      owner: ghUser.login,
      repo: repoName,
      base_tree: baseSha,
      tree: treeItems,
    });
    const { data: commit } = await octokit.git.createCommit({
      owner: ghUser.login,
      repo: repoName,
      message: `feat: AgentForge generated project — ${project.name}\n\nGenerated ${files.length} files using orchestrated AI agents.\nTemplate: ${project.template ?? "custom"}`,
      tree: tree.sha,
      parents: [baseSha],
    });
    await octokit.git.updateRef({
      owner: ghUser.login,
      repo: repoName,
      ref: "heads/main",
      sha: commit.sha,
    });

    // Encrypt token before storing
    const encryptedToken = await encryptSecret(token);
    await admin.from("github_connections").upsert(
      {
        user_id: user.id,
        login: ghUser.login,
        token_enc: encryptedToken,
        scope: ["repo"],
        repo_url: repo.html_url,
        commit_sha: commit.sha,
      },
      { onConflict: "user_id" }
    );

    await admin.from("audit_logs").insert({
      user_id: user.id,
      project_id: id,
      actor: user.id,
      action: "github.push",
      resource: "repo",
      resource_id: repo.html_url,
      metadata: { repoUrl: repo.html_url, commitSha: commit.sha, fileCount: files.length },
    });

    return NextResponse.json({ repoUrl: repo.html_url, commitSha: commit.sha, fileCount: files.length });
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : String(err);
    return NextResponse.json({ error: msg }, { status: 500 });
  }
}
