ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_versions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_files ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.agent_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.deployments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.exports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.provider_keys ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.provider_configs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.model_preferences ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.github_connections ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cloudflare_connections ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "users_own" ON public.users FOR ALL USING (auth.uid() = id);
CREATE POLICY "projects_owner" ON public.projects FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "versions_owner" ON public.project_versions FOR ALL USING (EXISTS (SELECT 1 FROM public.projects p WHERE p.id = project_id AND p.user_id = auth.uid()));
CREATE POLICY "files_owner" ON public.project_files FOR ALL USING (EXISTS (SELECT 1 FROM public.projects p WHERE p.id = project_id AND p.user_id = auth.uid()));
CREATE POLICY "conversations_owner" ON public.conversations FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "messages_owner" ON public.messages FOR ALL USING (EXISTS (SELECT 1 FROM public.conversations c WHERE c.id = conversation_id AND c.user_id = auth.uid()));
CREATE POLICY "runs_owner" ON public.agent_runs FOR ALL USING (EXISTS (SELECT 1 FROM public.projects p WHERE p.id = project_id AND p.user_id = auth.uid()));
CREATE POLICY "tasks_owner" ON public.tasks FOR ALL USING (EXISTS (SELECT 1 FROM public.projects p WHERE p.id = project_id AND p.user_id = auth.uid()));
CREATE POLICY "deployments_owner" ON public.deployments FOR ALL USING (EXISTS (SELECT 1 FROM public.projects p WHERE p.id = project_id AND p.user_id = auth.uid()));
CREATE POLICY "exports_owner" ON public.exports FOR ALL USING (EXISTS (SELECT 1 FROM public.projects p WHERE p.id = project_id AND p.user_id = auth.uid()));
CREATE POLICY "provider_keys_owner" ON public.provider_keys FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "provider_configs_owner" ON public.provider_configs FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "model_prefs_owner" ON public.model_preferences FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "github_conn_owner" ON public.github_connections FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "cf_conn_owner" ON public.cloudflare_connections FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "audit_read_own" ON public.audit_logs FOR SELECT USING (auth.uid() = user_id);
